/* ============================================================
   KAADU — dataset
   Replace or extend these two arrays with real data. Every field
   is optional except n / s / c / g; the UI degrades gracefully.
     n  common name        m  Malayalam (script)    r  romanised
     s  scientific name    f  family                c  category
     g  glyph key (see ART in app.js)               b  one-line blurb
     d  description        w  where                 t  when
     u  uses               e  note / endemism flag
   ============================================================ */

/* ============================================================
   KAADU — campus flora
   The 69 species recorded on the IHRD Pazhayannur campus
   (survey of 5 March 2026, identified by Dr. Udayan P.S.).
   Local names (r) follow the survey list; m is the same name in
   Malayalam script where the survey name is Malayalam.
     n  common name        m  Malayalam script      r  local name
     s  scientific name    f  family                c  category
     g  plate glyph        b  one-line blurb        d  description
     w  where it grows     t  when (flower/fruit)   u  uses
     e  status (first word drives the card flag)
     a  other names        k  caution
   ============================================================ */

const FLORA = [
/* ---------------- Trees ---------------- */
{n:"Teak",m:"തേക്ക്",r:"Thekku",s:"Tectona grandis",f:"Lamiaceae",c:"Trees",g:"broad",
 b:"Huge rough leaves, pale flower sprays and famously stable timber.",
 d:"A tall deciduous tree whose leaves can be larger than a dinner plate and feel like sandpaper; crushed young leaves stain red. The golden-brown heartwood is oily enough to resist termites and rot. Nilambur in Malappuram holds Conolly's Plot, planted in 1842 and still standing as the oldest teak plantation in the world.",
 w:"Moist and dry deciduous forest, plantations, homesteads",t:"Flowers June to September; bare in the dry months",u:"Furniture, doors, boats, construction timber"},
{n:"Dhaman",m:"ചടച്ചി",r:"Chadachi",s:"Grewia tiliifolia",f:"Malvaceae",c:"Trees",g:"broad",
 b:"A lime-leaved forest tree with tough, springy wood and small yellow flowers.",
 d:"A medium-sized tree with lopsided, finely toothed leaves and clusters of small yellow flowers in the leaf axils, followed by round drupes. Dhaman wood is elastic and strong, which made it the traditional choice for tool handles, cart shafts and oars.",
 w:"Moist deciduous forest; tropical Africa and India to Indo-China",u:"Tool handles, oars, cart poles; bark in folk medicine, including a hair wash to reduce hair fall"},
{n:"Arjun tree",m:"നീർമരുത്",r:"Neermaruthu",s:"Terminalia arjuna",f:"Combretaceae",c:"Trees",g:"leaf",
 b:"A riverbank tree whose smooth, pinkish bark is Ayurveda's classic heart medicine.",
 d:"A large, often buttressed tree with smooth grey-pink bark that peels away in flakes. Dull yellow flower spikes give way to hard fruits with five woody, ridge-like wings. It grows naturally along streams and rivers, which is where the Malayalam names ‘neer’ and ‘aattu’ maruthu (water, river) come from.",
 w:"River and stream banks across India and Sri Lanka; widely planted",t:"Flowers April to July",u:"Bark used in Ayurveda for heart and circulatory complaints; shade and riverbank planting",a:"Attumaruthu (ആറ്റുമരുത്), Vellamatthi"},
{n:"Sandalwood",m:"ചന്ദനം",r:"Chandanam",s:"Santalum album",f:"Santalaceae",c:"Trees",g:"leaf",
 b:"A root parasite that borrows from its neighbours while it grows.",
 d:"Sandalwood attaches to the roots of other plants through small suckers called haustoria, and grows poorly without a host. The fragrance is in the heartwood, which takes fifteen years or more to form. In Kerala the natural stands are concentrated around Marayoor in Idukki.",
 w:"Dry rain-shadow valleys; planted in homesteads",t:"Heartwood forms slowly, over 15+ years",u:"Oil, incense, carving, ritual paste",e:"Protected — felling and trade are regulated; IUCN lists it as Vulnerable"},
{n:"Mahua",m:"ഇലുപ്പ",r:"Eluppa",s:"Madhuca longifolia var. latifolia",f:"Sapotaceae",c:"Trees",g:"leaf",
 b:"The butter tree — fleshy, sweet flowers and seeds rich in fat.",
 d:"A spreading tree with leaves clustered at the tips of the branches. In the dry season it drops masses of creamy, fleshy flowers that are sugary enough to be eaten, dried or fermented. The seeds are pressed for a solid fat known as mahua or illipe butter.",
 w:"Dry deciduous forest and village land across India and Myanmar",t:"Flowers in the dry months, before the monsoon",u:"Edible flowers, seed fat for cooking and soap, timber; used in Ayurveda and folk medicine",a:"Ilippa (ഇലിപ്പ), Irippa (ഇരിപ്പ)"},
{n:"Cluster fig",m:"അത്തി",r:"Athi",s:"Ficus racemosa",f:"Moraceae",c:"Trees",g:"fig",
 b:"Figs grow in bunches straight from the trunk — one of Kerala's four sacred figs.",
 d:"A large, often buttressed fig that bears its fruit in dense clusters on short leafless shoots from the trunk and main branches. The figs ripen from green to red and feed bats, birds, squirrels and monkeys. Athi is one of the Nalpamaram, the four fig trees whose barks are combined in Ayurvedic preparations.",
 w:"Semi-evergreen and deciduous forest, riversides and plains",t:"Figs through much of the year",u:"Edible figs; bark, latex and fruit used in Ayurveda (Nalpamaram); shade",a:"Atthi-al (അത്തി-ആൽ)"},
{n:"White fig",m:"കല്ലാൽ",r:"Kallal",s:"Ficus virens",f:"Moraceae",c:"Trees",g:"fig",
 b:"A strangler fig that flushes pink new leaves twice a year.",
 d:"A semi-deciduous fig whose seeds can sprout on another tree, send roots down and eventually strangle its host. Its crown can grow wider than the tree is tall. In India it drops and renews its leaves in spring and again around the monsoon, when the new growth comes in reddish pink.",
 w:"Tropical and subtropical Asia to northern Australia; roadsides and temple grounds",t:"Leaf flush in spring and around the monsoon",u:"Shade; young shoots are eaten as a vegetable in parts of Asia; figs feed birds and bats"},
{n:"Bullet wood",m:"ഇലഞ്ഞി",r:"Elanji",s:"Mimusops elengi",f:"Sapotaceae",c:"Trees",g:"leaf",
 b:"Small star-shaped flowers that keep their scent long after they dry.",
 d:"A dense, dark evergreen shade tree often planted in temple courtyards. The small cream flowers fall in the early morning and are gathered for garlands; unusually, they hold their fragrance for days after drying. The orange berries are edible.",
 w:"Temple grounds, avenues, homesteads",t:"Flowers March to July",u:"Shade, garlands, hard timber; bark used to strengthen gums in traditional medicine"},
{n:"Strychnine tree",m:"കാഞ്ഞിരം",r:"Kanjiram",s:"Strychnos nux-vomica",f:"Loganiaceae",c:"Trees",g:"leaf",
 b:"Glossy leaves, orange fruit and flat grey seeds that are seriously poisonous.",
 d:"A medium-sized deciduous tree with shiny leaves marked by three strong veins from the base. The hard orange fruit holds disc-shaped seeds that contain strychnine and brucine. Traditional systems use the seed only after long purification.",
 w:"Dry and moist deciduous forest, village land",t:"Fruits December to March",u:"Regulated use in Ayurveda and homoeopathy; bitter timber resists insects",k:"Seeds and bark are highly toxic. Do not taste or handle the seeds carelessly."},
{n:"Indian beech",m:"ഉങ്ങ്",r:"Ongu",s:"Pongamia pinnata",f:"Fabaceae",c:"Trees",g:"pinnate",
 b:"A tough, nitrogen-fixing shade tree whose seed oil once lit lamps.",
 d:"A hardy legume with glossy compound leaves and drooping sprays of lilac-pink pea flowers, followed by flat woody pods holding one or two seeds. It tolerates drought, salt and poor soil, which is why it is planted along roads and canals. Trees start bearing pods at about five years.",
 w:"Native to South and Southeast Asia; roadsides, canal banks, coasts",t:"Flowers in the hot months before the monsoon",u:"Seed oil for lamps, soap, leather work and biodiesel; shade, green manure, fodder",k:"The seed oil is bitter and toxic (karanjin) and is not edible."},
{n:"Sandpaper tree",m:"പറുവ",r:"Paruva",s:"Streblus asper",f:"Moraceae",c:"Trees",g:"leaf",
 b:"Leaves rough enough to sand wood, twigs used as toothbrushes.",
 d:"A small, crooked tree with stiff, irregularly toothed leaves whose surface is rough like sandpaper. The branches bleed milky latex when cut. A twig with a chewed, frayed end was a traditional toothbrush across South and Southeast Asia, and in Thailand the bark has been used for paper for centuries.",
 w:"Dry regions across South and Southeast Asia",u:"Tooth-cleaning twigs, leaves as abrasive, bark paper; used in Ayurveda",a:"Parakam, Tinda-paruva"},
{n:"Hill mango",m:"ഇടിഞ്ഞിൽ",r:"Edinjil",s:"Commiphora caudata",f:"Burseraceae",c:"Trees",g:"pinnate",
 b:"Green bark with reddish stripes that peels off in thin scales.",
 d:"A small tree of dry, rocky places, recognised by its green bark streaked with reddish brown that flakes away in papery scales. It has compound leaves, tiny greenish-yellow flowers and round fruits with yellow flesh. It belongs to the same genus as myrrh and guggul.",
 w:"Dry hill slopes of peninsular India and Sri Lanka",u:"Roots and leaves in folk medicine for fever and joint pain; bark paste applied to set fractures",a:"Kizhingil (കിഴിഞ്ഞിൽ), Kilimaram (കിളിമരം)"},
{n:"Indian almond",m:"ബദാം",r:"Badam",s:"Terminalia catappa",f:"Combretaceae",c:"Trees",g:"broad",
 b:"Branches in flat tiers, like a stack of plates.",
 d:"A coastal tree with large, glossy leaves that turn red before falling, often twice a year. Its horizontal branches grow in distinct tiers, giving deep shade. The kernel inside the hard, flattened fruit tastes like almond, though the tree is not related to the true almond.",
 w:"Coasts, roadsides and school compounds throughout the tropics",t:"Fruits most of the year",u:"Shade, edible kernel, leaves used in aquariums and for dye"},
{n:"Lindley's aporosa",m:"വെട്ടി",r:"Vetti",s:"Aporosa cardiosperma",f:"Phyllanthaceae",c:"Trees",g:"leaf",
 b:"A small forest tree with separate male and female trees.",
 d:"A small evergreen tree of lowland forests. Male and female flowers grow on different trees: the males in short yellow catkin-like spikes, the females in small furry clusters that become little capsules. It is a common understorey tree in Kerala's midlands.",
 w:"Peninsular India and Sri Lanka; lowland evergreen and semi-evergreen forest",u:"Root decoction used in folk medicine for jaundice, fever and headache; firewood",a:"Aechil (ഏച്ചിൽ), Kotili (കൊറ്റിലി)"},
{n:"Indian elm",m:"ആവൽ",r:"Aaval",s:"Holoptelea integrifolia",f:"Ulmaceae",c:"Trees",g:"broad",
 b:"Round papery winged fruits that spin away on the wind.",
 d:"A tall deciduous tree whose leaves smell unpleasant when crushed. Small greenish-purple flowers appear on bare branches, followed by flat, round fruits with a papery wing around a single seed. It is one of the few members of the elm family native to the Indian plains.",
 w:"Deciduous forest and village land across India and Southeast Asia",u:"Timber; bark and leaves used in traditional medicine for swellings, skin disease and digestive complaints",a:"Aavil (ആവിൽ), Njettaval (ഞെട്ടാവൽ)"},
{n:"White dammar",m:"പന്തം",r:"Pantham",s:"Vateria indica",f:"Dipterocarpaceae",c:"Trees",g:"leaf",
 b:"A giant of the Ghats rainforest that bleeds fragrant white resin.",
 d:"A large evergreen tree that can reach 40 metres, with smooth grey bark blotched green and white. Wounded bark oozes a white aromatic resin used as incense, and the seed kernels yield a solid fat called piney tallow. It grows only in the Western Ghats and has become scarce through logging and habitat loss.",
 w:"Wet evergreen forest below 1,200 m in Kerala, Karnataka and Tamil Nadu",u:"Resin for incense and varnish, seed fat for candles and soap, timber for plywood",e:"Endemic to the Western Ghats; IUCN lists it as Vulnerable",a:"Paini (പയിനി), Vellappayin, Kunthirikkam"},
{n:"Indian oak",m:"ആറ്റുവഞ്ചി",r:"Aattuvanji",s:"Barringtonia acutangula",f:"Lecythidaceae",c:"Trees",g:"leaf",
 b:"Long strings of red flowers that open at night beside the water.",
 d:"A small riverside tree, also called the freshwater mangrove, with leaves crowded at the tips of the branches. Its flowers hang in long pendulous strings of red stamens that open after dark and fall by morning, carpeting the ground. The fibrous, four-angled fruit floats.",
 w:"Riverbanks, pond edges and water courses from India to Australia",u:"Fruit, seed, leaf and root used in Ayurveda and Unani; bark used as a fish poison in the past",a:"Attupezhu (ആറ്റുപേഴു), Neerpezhu (നീർപ്പേഴു)"},
{n:"Marotti",m:"മരോട്ടി",r:"Marotti",s:"Hydnocarpus pentandrus",f:"Achariaceae",c:"Trees",g:"broad",
 b:"Its seed oil was the main treatment for leprosy for centuries.",
 d:"A semi-deciduous tree up to 10 metres with round, woody fruits 6–10 cm across, each packed with 10–16 seeds. Chaulmoogra oil from the seeds was used against leprosy in Indian and Chinese medicine, adopted by Western doctors in the 1800s, and made injectable by chemist Alice Ball in 1916 — until sulfone drugs replaced it in the 1940s.",
 w:"Moist deciduous forest of the Western Ghats, Maharashtra to Kerala; also northeast India",t:"Flowers January to April; fruits August and September",u:"Seed oil for skin disease and, historically, leprosy",e:"Vulnerable (IUCN)"},
{n:"Kaim",m:"കടമ്പ്",r:"Kadambu",s:"Mitragyna parvifolia",f:"Rubiaceae",c:"Trees",g:"broad",
 b:"Tiny yellow flowers packed into perfect round balls.",
 d:"A deciduous tree up to about 15 metres with smooth, rounded leaves in opposite pairs. Its small yellow flowers are packed into globe-shaped heads. The fine-grained timber is used for furniture and turnery, and the leaves feed the caterpillars of the Commander butterfly.",
 w:"Dry and moist deciduous forest in India and Sri Lanka",u:"Timber; bark, root and leaf sap used in traditional medicine for fever, pain and swelling; butterfly host plant"},
{n:"Black catechu",m:"കരിങ്ങാലി",r:"Karinjali",s:"Senegalia catechu",f:"Fabaceae",c:"Trees",g:"pinnate",
 b:"A thorny acacia whose boiled heartwood gives katha for paan.",
 d:"A deciduous thorny tree with fine feathery leaves and pale yellow flower spikes, followed by flat pods. Boiling the dark heartwood gives catechu (katha), the astringent extract smeared on betel leaf and used in dyeing and tanning. Karingali water, made from the heartwood, is a common drinking water in Kerala homes.",
 w:"Dry deciduous forest in India and Myanmar",u:"Catechu (katha) for paan, dye and tanning; heartwood water; used in Ayurveda for skin and gum problems",a:"Khadira (Sanskrit)"},
{n:"Morinda",m:"മഞ്ഞപ്പാവട്ട",r:"Manjapavetta",s:"Morinda pubescens",f:"Rubiaceae",c:"Trees",g:"broad",
 b:"The root bark gives a red dye known as suranji.",
 d:"A small tree with pale brown bark, glossy opposite leaves and fragrant white flowers in round heads, followed by knobbly compound fruits. The root bark of three- to four-year-old trees yields morindone, a dye that colours cotton, silk and wool red, chocolate or purple.",
 w:"Moist and dry deciduous forest, Indo-Malaysia",t:"Flowers March to June",u:"Red dye (suranji); trunk used in traditional medicine as a tonic",a:"Manjanathi (മഞ്ഞണാത്തി)"},
{n:"Burma ironwood",m:"ഇരുൾ",r:"Irool",s:"Xylia xylocarpa",f:"Fabaceae",c:"Trees",g:"pinnate",
 b:"One of the hardest timbers in the forest, with pods that snap open.",
 d:"A large deciduous legume with twice-compound leaves and fluffy balls of pale yellow flowers. The flat, woody pods split and twist open sharply to fling out their seeds. The dark red heartwood is dense and heavy — heavier than water — and was prized for railway sleepers, bridges and carts.",
 w:"Deciduous forest of South and Southeast Asia",t:"Flowers in the dry season",u:"Heavy construction timber; edible seeds; used in traditional medicine"},
{n:"Spinous kino tree",m:"മുള്ളുവേങ്ങ",r:"Mulluvenga",s:"Bridelia retusa",f:"Phyllanthaceae",c:"Trees",g:"leaf",
 b:"Young trunks are armed with stout conical spines.",
 d:"A medium-sized deciduous tree; young stems carry sharp conical spines that fall away as the bark matures. Clusters of small greenish-yellow flowers become purplish-black berries eaten by birds. The leaves turn red before they drop.",
 w:"Semi-evergreen and deciduous forest and the plains, Indo-Malaya",u:"Bark used in Ayurveda and folk medicine for rheumatism and pain; timber; fodder",a:"Mullankkayini (മുള്ളങ്കായിനി)"},
{n:"Indian cherry",m:"പശക്കായ മരം",r:"Pasakaya maram",s:"Cordia dichotoma",f:"Cordiaceae",c:"Trees",g:"broad",
 b:"The glue berry — its ripe fruit pulp is sticky enough to use as paste.",
 d:"A small to medium deciduous tree with a short trunk and spreading crown. White flowers open only at night. The shiny yellow to pinkish fruits turn black as they ripen, and the pulp becomes so sticky it was used as a glue — the source of the Malayalam name ‘pasa’ (glue).",
 w:"Tropical Asia to Australia; village land and dry forest",u:"Unripe fruit pickled or cooked as a vegetable; fruit glue; leaves as fodder; used in Unani medicine",a:"Viri, Vidi"},
{n:"China doll tree",m:"പൂപ്പാതിരി",r:"Poopathiri",s:"Radermachera sinica",f:"Bignoniaceae",c:"Ornamental",g:"pinnate",
 b:"Sold everywhere as a houseplant, but it grows into a real tree.",
 d:"In the wild this is a tree up to 30 metres tall with glossy, twice-compound leaves. It bears large white trumpet flowers that open at night and are strongly scented, followed by long, curved seed pods that earn it the name serpent tree. Most people know it as a small potted plant.",
 w:"Native to subtropical mountains of southern China and Taiwan; planted as an ornamental",t:"Flowers in the hot season",u:"Ornamental tree and houseplant",e:"Introduced from southern China and Taiwan",a:"Serpent tree, emerald tree"},

/* ---------------- Fruit ---------------- */
{n:"Mango",m:"മാവ്",r:"Maavu",s:"Mangifera indica",f:"Anacardiaceae",c:"Fruit",g:"leaf",
 b:"Every seedling tree is its own variety — good for pickle even when poor for eating.",
 d:"A large evergreen tree that turns dusty cream when it flowers in the dry months and fruits with the first pre-monsoon showers. Kerala recognises hundreds of local types, and most backyard trees are grown from seed, so each is slightly different. Tender mangoes go into kadumanga pickle; ripe ones are eaten fresh.",
 w:"Homesteads, plains and midlands",t:"Flowers December to February; fruits April to June",u:"Fruit, pickle, timber; leaves used in festival decorations"},
{n:"Jackfruit",m:"പിലാവ്",r:"Pilavu",s:"Artocarpus heterophyllus",f:"Moraceae",c:"Fruit",g:"broad",
 b:"Kerala's state fruit — the largest fruit that grows on any tree.",
 d:"The fruits grow straight from the trunk and thick branches, a habit called cauliflory, and can weigh more than 30 kg. Kerala distinguishes the firm-fleshed varikka from the soft, juicy koozha. Almost nothing is wasted: the unripe fruit is cooked, the seeds are roasted, and the golden timber is used for furniture and temple drums.",
 w:"Homesteads and midlands up to about 1,200 m",t:"Fruits March to July",u:"Fruit, vegetable, seeds, timber, yellow dye",a:"Plavu (പ്ലാവ്)"},
{n:"Sapota",m:"സപ്പോട്ട",r:"Sapotta",s:"Manilkara zapota",f:"Sapotaceae",c:"Fruit",g:"leaf",
 b:"Brown, malty fruit from the tree that gave the world chewing gum.",
 d:"A slow-growing evergreen tree with glossy leaves clustered at the branch tips. The rough brown fruit has sweet, grainy flesh that tastes of brown sugar. Its milky latex, chicle, was the original base of chewing gum. In India it is often grafted onto rootstock of its wild relative, khirni.",
 w:"Native to southern Mexico, Central America and the Caribbean; widely grown in India",t:"Fruits through much of the year",u:"Fresh fruit, milkshakes; latex (chicle); hard timber",e:"Introduced from tropical America",a:"Chikoo, sapodilla"},
{n:"Khirni",m:"മുള്ളുപാല",r:"Mullupala",s:"Manilkara hexandra",f:"Sapotaceae",c:"Fruit",g:"leaf",
 b:"A wild cousin of the sapota with sweet little yellow fruit.",
 d:"A slow-growing, hardy evergreen tree reaching 12–25 metres, with rough grey bark and milky sap. The small yellow berries are sweet and edible, fresh or dried. Its wood is very hard and heavy, and seedlings are widely used as rootstock for grafted sapota.",
 w:"Dry forest and village land in India, Sri Lanka and Indo-China",t:"Fruits in the hot months",u:"Edible fruit, heavy timber for posts and beams, rootstock for sapota",a:"Milk tree, Ceylon ironwood"},
{n:"Guava",m:"പേരക്ക",r:"Perakka",s:"Psidium guajava",f:"Myrtaceae",c:"Fruit",g:"leaf",
 b:"Smooth, flaking bark and fruit the crows always find first.",
 d:"A small tree with smooth, copper-coloured bark that peels in thin sheets and leaves with deeply sunken veins. It fruits within a few years of planting and is grown in almost every Kerala homestead. The leaves are brewed as a home remedy for stomach upsets.",
 w:"Native to tropical America; homesteads throughout Kerala",t:"Two crops, peaking August to November",u:"Fresh fruit, jam, juice; leaf decoction",e:"Introduced from tropical America"},
{n:"Strawberry guava",r:"Chinese guava",s:"Psidium cattleyanum",f:"Myrtaceae",c:"Fruit",g:"leaf",
 b:"Small red or yellow guavas with a tart, strawberry-like flavour.",
 d:"A shrub or small tree with smooth grey to reddish-brown bark and small, glossy, leathery leaves. The thin-skinned fruits, about 4 cm long, ripen deep red or yellow depending on the variety. Despite the local name it comes from Brazil, not China.",
 w:"Native to Brazil and neighbouring South America; garden plant in Kerala",t:"Begins fruiting at 3–6 years old",u:"Fresh fruit, jam, juice; hard wood for tool handles",e:"Invasive — listed among the world's 100 worst invasive species; keep it in the garden",a:"Cattley guava, cherry guava"},
{n:"Rambutan",m:"റമ്പൂട്ടാൻ",r:"Rambutan",s:"Nephelium lappaceum",f:"Sapindaceae",c:"Fruit",g:"berry",
 b:"A hairy red cousin of the lychee, now a Kerala orchard crop.",
 d:"An evergreen tree from Southeast Asia bearing clusters of red or yellow fruit covered in soft, fleshy spines. Inside is sweet, translucent white flesh around a single seed. Kerala's climate suits it so well that harvests are staggered across the state: Thrissur trees fruit first, from about May.",
 w:"Native to Southeast Asia; orchards in central Kerala",t:"In Thrissur, flowers late January to mid-March and fruits in May",u:"Fresh fruit",e:"Introduced from Southeast Asia"},
{n:"Yellow mangosteen",m:"മഞ്ഞക്കുടംപുളി",r:"Manja kudampuli",s:"Garcinia xanthochymus",f:"Clusiaceae",c:"Fruit",g:"leaf",
 b:"A neat, pyramid-shaped tree with glossy leaves and sour yellow fruit.",
 d:"An evergreen tree up to 20 metres with horizontal branches that droop at the tips, giving a tidy conical outline. The long leathery leaves are glossy dark green. Its round yellow fruit has sharply acidic pulp around one or two seeds, and young plants are used as rootstock for mangosteen.",
 w:"Indo-Malesia; mostly cultivated",t:"Flowers and fruits through the year",u:"Fruit eaten raw or cooked, used for souring; rootstock for mangosteen",a:"Monthanpuli (മൊന്തൻപുളി), egg tree, sour mangosteen"},
{n:"Water apple",m:"ചാമ്പ",r:"Chamba",s:"Syzygium aqueum",f:"Myrtaceae",c:"Fruit",g:"leaf",
 b:"Crisp, bell-shaped fruit that tastes like a watery apple.",
 d:"A small tree with leathery leaves and fluffy white flowers. The waxy bell-shaped fruits range from white to pink or red and have crisp, watery flesh with a mild, sweet taste, like the inside of a watermelon. It is easily confused with the larger wax apple (Syzygium samarangense), also sold as chamba.",
 w:"Native to tropical Asia and Queensland; homestead gardens",u:"Fresh fruit; durable wood for tools",e:"Introduced from Southeast Asia",a:"Bell fruit, watery rose apple"},
{n:"Tamarind",m:"പുളി",r:"Puli",s:"Tamarindus indica",f:"Fabaceae",c:"Fruit",g:"pinnate",
 b:"Sour pods, dense shade, and a tree that outlives the house.",
 d:"A long-lived legume with fine feathery leaflets that fold together at night. The brown pods hold sticky, sour pulp that is a standard souring agent in South Indian cooking. Although it has grown in India for thousands of years, it originally came from tropical Africa.",
 w:"Roadsides, dry tracts, homesteads",t:"Pods ripen January to April",u:"Cooking, chutney, timber, shade",e:"Introduced from tropical Africa, in ancient times"},
{n:"Star gooseberry",m:"അരിനെല്ലി",r:"Arinelli",s:"Phyllanthus acidus",f:"Phyllanthaceae",c:"Fruit",g:"pinnate",
 b:"Pale, ribbed, very sour fruit crowded along the bare branches.",
 d:"A small bushy tree whose pale yellow, six- to eight-ribbed fruits grow in dense clusters directly on the branches. They are waxy, crisp and intensely sour, and stay firm when ripe — they are picked when they start to drop. Its origin is uncertain, possibly Madagascar, but it has been grown in South Asia since ancient times.",
 w:"Homestead gardens across South and Southeast Asia",t:"Fruits April to May and August to September in South India",u:"Pickles, preserves, chutneys, candied fruit; cooked leaves eaten",a:"Otaheite gooseberry, pulinelli"},
{n:"Java plum",m:"ഞാവൽ",r:"Njaval",s:"Syzygium cumini",f:"Myrtaceae",c:"Fruit",g:"leaf",
 b:"Purple fruit that stains the tongue and the road below.",
 d:"A large evergreen with glossy, aromatic leaves, common along riverbanks and in homesteads. The astringent, deep purple fruits ripen at the start of the monsoon and are eaten with salt. The seed powder is a long-standing folk remedy for diabetes.",
 w:"Riverbanks, homesteads, forest edges",t:"Fruits May to July",u:"Fruit, vinegar, timber; seed powder in folk medicine"},
{n:"Cashew",m:"കശുമാവ്",r:"Kasumav",s:"Anacardium occidentale",f:"Anacardiaceae",c:"Fruit",g:"leaf",
 b:"The nut hangs below the fruit, which is really a swollen stalk.",
 d:"A spreading evergreen tree brought from Brazil by the Portuguese. The juicy red or yellow ‘cashew apple’ is actually the swollen stalk; the true fruit is the kidney-shaped nut hanging below it. Kollam built an entire processing industry on it.",
 w:"Coastal laterite; Kollam and Kannur belts",t:"Harvest February to May",u:"Nut, cashew apple (fresh, juice, feni), shell oil",e:"Introduced from Brazil",k:"The raw shell contains a caustic oil. Nuts must be roasted or steamed before shelling."},
{n:"Lime",m:"ചെറുനാരകം",r:"Cherunaregam",s:"Citrus × aurantifolia",f:"Rutaceae",c:"Fruit",g:"leaf",
 b:"The small, thin-skinned lime squeezed into every glass of naranga vellam.",
 d:"A thorny shrub or small tree with fragrant white flowers and small round fruits that ripen from green to yellow. It is a natural hybrid within the citrus genus, hence the ‘×’ in its name. The juice is the base of Kerala's lime juice and lime pickle.",
 w:"Homestead gardens",t:"Fruits through much of the year",u:"Juice, pickle, cooking; peel oil",a:"Key lime, acid lime"},
{n:"Star fruit",m:"വലിയ ഇരുമ്പൻപുളി",r:"Valiya irumbampuli",s:"Averrhoa carambola",f:"Oxalidaceae",c:"Fruit",g:"pinnate",
 b:"Cut it across and every slice is a five-pointed star.",
 d:"A small tree with compound leaves and small pink-purple flowers borne on the branches. The waxy, five-ridged fruits ripen from green to golden yellow and range from sour to sweet. It is a larger relative of the irumbanpuli (bilimbi) found in most Kerala gardens.",
 w:"Native to Southeast Asia; homestead gardens",t:"Fruits through much of the year",u:"Fresh fruit, juice, pickle",e:"Introduced from Southeast Asia",k:"People with kidney disease should not eat star fruit: it contains oxalate and caramboxin, a neurotoxin that damaged kidneys cannot clear."},
{n:"Soursop",m:"മുള്ളാത്ത",r:"Mullatha",s:"Annona muricata",f:"Annonaceae",c:"Fruit",g:"leaf",
 b:"A spiny green fruit with white, tangy-sweet custard inside.",
 d:"A small evergreen tree with glossy leaves and large, heart-shaped green fruits covered in soft spines. The flesh is white, fibrous and juicy, with a flavour between pineapple and strawberry. It is widely promoted online as a cancer cure; there is no clinical evidence for this.",
 w:"Native to tropical America; homestead gardens",u:"Fresh fruit, juice, ice cream",e:"Introduced from tropical America",k:"The fruit and especially the seeds and leaves contain annonacin, a neurotoxin linked to atypical Parkinsonism in heavy consumers. Do not use leaf tea as medicine."},
{n:"White mulberry",r:"Mulberry",s:"Morus alba",f:"Moraceae",c:"Fruit",g:"broad",
 b:"The leaf that feeds the silkworm, and sweet fruit for everyone else.",
 d:"A fast-growing shrub or small tree with glossy leaves that vary in shape, even on one branch. The small fruits ripen from white or pink to dark purple. Its leaves are the staple food of the domestic silkworm, which is why it has been planted wherever silk is made.",
 w:"Native to northern China; grown widely for sericulture",t:"Fruits in the dry season",u:"Fruit, jam; leaves for silkworms and fodder",e:"Introduced from China"},
{n:"Indian gooseberry",m:"നെല്ലി",r:"Nelli",s:"Phyllanthus emblica",f:"Phyllanthaceae",c:"Fruit",g:"pinnate",
 b:"Sour, then unaccountably sweet if you drink water after it.",
 d:"A deciduous tree with feathery-looking foliage made of tiny leaflets along slender branchlets. The pale green, translucent fruits are very high in vitamin C. With kadukka and thanni, nelli completes triphala, one of the most used preparations in Ayurveda.",
 w:"Homesteads; dry and moist deciduous forest",t:"Fruits October to February",u:"Fruit, pickle, hair oil, triphala",a:"Amla"},
{n:"Hog plum",m:"അമ്പഴം",r:"Ambazham",s:"Spondias pinnata",f:"Anacardiaceae",c:"Fruit",g:"pinnate",
 b:"Sour green fruit that goes into Kerala's ambazhanga pickle and curry.",
 d:"A deciduous tree with compound leaves clustered at the branch tips and sprays of small yellowish-white flowers. The oval fruits are fleshy and sour with a fibrous stone, yellow when ripe. Unripe ambazhanga is pickled or cooked into curries.",
 w:"Deciduous forest and homesteads, Indo-Malesia",u:"Pickle, curry, chutney; fruit, leaf and bark used in Ayurveda for dysentery and indigestion",a:"Kattambazham (കാട്ടമ്പഴം), wild mango"},

/* ---------------- Palms ---------------- */
{n:"Fishtail palm",m:"ആനപ്പന",r:"Aanapana",s:"Caryota urens",f:"Arecaceae",c:"Palms",g:"palm",
 b:"Flowers once, from the top downward, then dies.",
 d:"A solitary palm up to 18 metres with enormous twice-divided leaves whose leaflets are shaped like fish tails. After many years it flowers, producing hanging clusters up to 3 m long, starting at the crown and working down the trunk; when the lowest cluster has fruited, the palm dies. The Malayalam name means ‘elephant palm’ — its leaves are fed to elephants.",
 w:"Native to India, Sri Lanka and Southeast Asia; forest edges and homesteads",t:"Flowers once, after many years",u:"Sap for toddy and jaggery, trunk starch like sago, strong kithul fibre, elephant fodder",a:"Olatti (ഓലട്ടി), Choondappana (ചൂണ്ടപ്പന), toddy palm"},
{n:"Ruffled fan palm",r:"Ruffled fan palm",s:"Licuala grandis",f:"Arecaceae",c:"Palms",g:"palm",
 b:"Round, undivided leaves pleated like a paper fan.",
 d:"A slow-growing understorey palm whose leaves are almost perfectly round, stiffly pleated and undivided, unlike most fan palms. It bears round fruits that ripen from green to red. In its native rainforest it grows in shade, and it scorches in full sun.",
 w:"Native to the rainforests of Vanuatu; shade gardens",u:"Ornamental",e:"Introduced from Vanuatu",a:"Vanuatu fan palm"},
{n:"Areca palm",r:"Butterfly palm",s:"Dypsis lutescens",f:"Arecaceae",c:"Palms",g:"palm",
 b:"Clumps of golden canes and arching fronds.",
 d:"A clustering palm that sends up many slender, yellowish, cane-like stems, forming a vase shape 6–12 metres tall. The arching fronds have yellow midribs, and the fruit ripens from yellow to purple-black. It is one of the most widely sold indoor palms in the world. Recent treatments place it in Chrysalidocarpus.",
 w:"Native to Madagascar; gardens and houseplants worldwide",u:"Ornamental, indoor plant; formerly fibre for fishing nets in Madagascar",e:"Introduced from Madagascar",a:"Golden cane palm, yellow palm"},
{n:"Foxtail palm",r:"Fox tail palm",s:"Wodyetia bifurcata",f:"Arecaceae",c:"Palms",g:"palm",
 b:"Leaves so finely divided they look like a bushy fox's tail.",
 d:"A single-trunked palm 6–15 metres tall whose fronds carry hundreds of leaflets radiating in all directions. It was unknown to science until a 1968 forestry survey and was only formally described in 1983. The genus is named after Wodyeti, an Aboriginal man of the Cape Melville area who knew the plants of the region.",
 w:"Wild only among granite boulders in the Cape Melville range, Queensland, Australia",u:"Ornamental avenue and garden palm",e:"Introduced from Australia"},

/* ---------------- Flowering ---------------- */
{n:"Golden shower",m:"കണിക്കൊന്ന",r:"Kani konna",s:"Cassia fistula",f:"Fabaceae",c:"Flowering",g:"pod",
 b:"Kerala's state flower, and the whole visual of Vishu.",
 d:"Long chains of bright yellow flowers hang from almost bare branches in the weeks before the monsoon, which is why they fill the Vishu kani. The flowers are followed by long, dark cylindrical pods that stay on the tree for months.",
 w:"Roadsides, homesteads, deciduous forest",t:"Flowers March to May",u:"Festival flowers, ornamental; pod pulp used as a mild laxative in Ayurveda"},
{n:"Flame of the forest",m:"പിലാശ്",r:"Pilasu",s:"Butea monosperma",f:"Fabaceae",c:"Flowering",g:"pinnate",
 b:"Bare branches covered in flaming orange-red flowers.",
 d:"A small, crooked deciduous tree with large leaves of three leaflets. In the dry season it drops its leaves and covers itself in dense clusters of velvety orange-red flowers shaped like parrot beaks. Each flat pod holds a single seed, which is what monosperma means.",
 w:"Dry deciduous forest and open land across tropical Asia",t:"Flowers January to March, while leafless",u:"Dye from flowers, gum (Bengal kino), leaf plates; bark and seed used in Ayurveda",a:"Plasu (പ്ളാശ്), Chamatha (ചമത)"},
{n:"Hibiscus",m:"ചെമ്പരത്തി",r:"Chembarathi",s:"Hibiscus rosa-sinensis",f:"Malvaceae",c:"Flowering",g:"flower5",
 b:"One day per flower, and a new one every morning.",
 d:"An evergreen shrub grown as a hedge and a temple flower. Each flower lasts only a day. Crushed leaves and flowers make a traditional slippery hair wash, and the red flower is offered in temples.",
 w:"Hedges, gardens, temple grounds",t:"Flowers year round",u:"Hair wash, ritual, ornamental, tea",a:"Shoe flower"},
{n:"Golden dewdrop",r:"Duranta",s:"Duranta erecta",f:"Verbenaceae",c:"Flowering",g:"flower5",
 b:"Hedges of lilac flowers followed by drooping golden berries.",
 d:"A fast-growing shrub, often clipped into hedges, with hanging sprays of lilac-blue or white flowers and bunches of small golden-yellow berries. The flowers are a favourite of butterflies, and birds eat the berries without harm.",
 w:"Native to the Caribbean and Central and South America; hedges throughout Kerala",t:"Flowers much of the year",u:"Hedge and ornamental shrub; butterfly nectar plant",e:"Introduced from tropical America",k:"The berries contain saponins and are toxic to people and pets. Keep children from eating them."},
{n:"Garlic vine",m:"വെള്ളുള്ളിച്ചെടി",r:"Vellulli chedi",s:"Mansoa alliacea",f:"Bignoniaceae",c:"Flowering",g:"flower5",
 b:"Crush a leaf and it smells of garlic — it isn't related at all.",
 d:"A semi-woody climber with lavender trumpet flowers that fade to pale lilac and white, so one plant shows several shades at once. It blooms heavily a couple of times a year. The crushed leaves smell strongly of garlic, and in its native range they are used as a garlic substitute.",
 w:"Native to tropical America, Mexico to Brazil; garden fences and pergolas",t:"Heavy flushes of flowers twice a year",u:"Ornamental climber; leaves as garlic substitute; folk remedy for colds; mosquito repellent",e:"Introduced from tropical America"},
{n:"Parrot's beak",r:"Parrot beak",s:"Heliconia psittacorum × spathocircinata",f:"Heliconiaceae",c:"Flowering",g:"bamboo",
 b:"Upright flowerheads of glossy bracts on banana-like stems.",
 d:"A garden hybrid of two South American heliconias, grown for its upright heads of waxy, boat-shaped bracts in yellow, orange or red. It forms clumps 1–2 metres tall with leaves like small banana leaves. Popular cultivars include ‘Golden Torch’, and the cut stems last well in arrangements.",
 w:"Parent species native to tropical South America and the Caribbean; gardens and landscaping",t:"Flowers much of the year in the humid tropics",u:"Ornamental, cut flowers",e:"Introduced from tropical America"},

/* ---------------- Medicinal ---------------- */
{n:"Neem",m:"ആര്യവേപ്പ്",r:"Aaryaveppu",s:"Azadirachta indica",f:"Meliaceae",c:"Medicinal",g:"pinnate",
 b:"Every part of it is bitter, and that is the point.",
 d:"A hardy evergreen tree with toothed, sickle-shaped leaflets and small scented white flowers. Drier ground suits it, so it is commoner in the south and along the coast than in the hills. Leaf and seed extracts are long-standing garden pesticides, and the twigs are still used as toothbrushes.",
 w:"Coastal and dry tracts, roadsides, homesteads",t:"Flowers March to May",u:"Natural pesticide, seed oil, medicine for skin complaints, timber"},
{n:"Kurchi",m:"കുടകപ്പാല",r:"Kudakapala",s:"Holarrhena pubescens",f:"Apocynaceae",c:"Medicinal",g:"leaf",
 b:"Its bark, kutaja, has been Ayurveda's dysentery remedy for centuries.",
 d:"A small deciduous tree with milky sap, opposite leaves and clusters of fragrant white flowers, followed by long paired pods with silky-tufted seeds. The bark (kutaja) and seeds (indrayava) are standard Ayurvedic remedies for dysentery and diarrhoea, and the bark was once traded from the Malabar coast as ‘Tellicherry bark’.",
 w:"Deciduous forest across India",t:"Flowers in the hot months",u:"Bark and seeds used in Ayurveda for dysentery; light wood for carving",a:"Kutaja, Tellicherry bark"},
{n:"Leafy milk hedge",m:"മുള്ളുകള്ളി",r:"Mullukalli",s:"Euphorbia nivulia",f:"Euphorbiaceae",c:"Medicinal",g:"leaf",
 b:"A spiny succulent tree full of stinging white latex.",
 d:"A succulent that grows into a small tree up to 9 metres, with thick, jointed green branches studded with paired spines. Fleshy leaves up to 25 cm appear at the branch tips in the wet season and fall in the dry. It is often planted as a living fence.",
 w:"Rocky hillsides and dry scrub in India, Sri Lanka, Pakistan and Myanmar; hedges",u:"Living fence; leaf juice and root bark in folk medicine",a:"Elakkalli, Kallippala",k:"The milky latex is caustic. Keep it away from eyes and skin."},
{n:"Wild croton",m:"നാഗദന്തി",r:"Nagadanthi",s:"Baliospermum solanifolium",f:"Euphorbiaceae",c:"Medicinal",g:"broad",
 b:"A strong purgative herb of Ayurveda, known as danti.",
 d:"A leafy subshrub whose broad leaves are often three-lobed. It bears small greenish-yellow flowers and three-lobed capsules about a centimetre long. Its root, danti, is a powerful purgative in Ayurveda.",
 w:"Indo-Malesia; forest edges and medicinal gardens",u:"Root used in Ayurveda as a purgative and for piles, jaundice and skin disease",a:"Danti (ദന്തി), Dantika (ദന്തിക)",k:"Strongly purgative; the seeds are toxic. Use only under proper supervision."},
{n:"Bael",m:"കൂവളം",r:"Koovalam",s:"Aegle marmelos",f:"Rutaceae",c:"Medicinal",g:"pinnate",
 b:"Three-part leaves, thorns, and a fruit with a shell you have to crack.",
 d:"A spiny deciduous tree with leaves of three leaflets, closely associated with Shiva temples. The hard-shelled fruit contains aromatic orange pulp that is made into a cooling drink. The unripe fruit is a long-standing remedy for stomach trouble.",
 w:"Temple grounds and dry tracts",t:"Fruits March to June",u:"Sherbet, medicine, ritual leaves"},
{n:"Lesser galangal",m:"ചിറ്റരത്ത",r:"Chittaratha",s:"Alpinia calcarata",f:"Zingiberaceae",c:"Medicinal",g:"bamboo",
 b:"A ginger relative whose aromatic rhizome goes into cough and joint remedies.",
 d:"A clump-forming, ginger-like herb with narrow, glossy leaves and white flowers marked with red and yellow. The aromatic rhizome is warming and pungent. It is grown in Kerala as a medicinal crop and is used as rasna in many Ayurvedic preparations.",
 w:"Indo-Malesia; medicinal gardens and homesteads",u:"Rhizome used in Ayurveda for cough, sore throat, rheumatism and digestion",a:"Kolinchi (കോലിഞ്ചി), snap ginger"},
{n:"Sabah snake grass",m:"വിഷമൂലി",r:"Visha mooli",s:"Clinacanthus nutans",f:"Acanthaceae",c:"Medicinal",g:"leaf",
 b:"A Southeast Asian herb kept in Kerala gardens as a snakebite plant.",
 d:"A slender shrub with ribbed stems, narrow opposite leaves and tubular dull-red flowers with green bases. In Thailand and Malaysia it is a folk remedy for insect stings, rashes and snakebite, which is where both its English and Malayalam names come from.",
 w:"Native to Southeast Asia; grown in Kerala medicinal gardens",u:"Folk medicine for stings, rashes and sore throat",e:"Introduced from Southeast Asia",a:"Vishapacha (വിഷപ്പച്ച)",k:"Folk use only — it is not a treatment for snakebite. A snakebite needs anti-venom at a hospital."},
{n:"Indian ipecac",m:"ആസ്ത്മച്ചെടി",r:"Asthma chedi",s:"Vincetoxicum indicum",f:"Apocynaceae",c:"Medicinal",g:"leaf",
 b:"A slender climber long used for asthma and bronchitis.",
 d:"A thin, softly hairy twining climber with opposite oval leaves and small greenish-purple or greenish-yellow star-shaped flowers. Better known by its older name Tylophora indica, its root and leaves have been used for asthma, bronchitis and whooping cough.",
 w:"Deciduous forest, bushes and thickets across Indo-Malesia",u:"Root and leaf used in Ayurveda for asthma, bronchitis and dysentery",a:"Vallippala (വള്ളിപ്പാല), Tylophora indica, emetic swallow-wort",k:"The root causes vomiting in larger doses."},
{n:"Birch-leaved acalypha",m:"ബാലമുഞ്ഞ",r:"Bala munja",s:"Acalypha fruticosa",f:"Euphorbiaceae",c:"Medicinal",g:"leaf",
 b:"A bushy shrub with tiny catkins hidden among the leaves.",
 d:"An erect, much-branched shrub with small oval, toothed leaves like a birch. Short spikes carry both male and female flowers, followed by small three-lobed capsules. The leaves are used in folk medicine across southern India and Africa.",
 w:"Dry scrub across the Old World tropics",u:"Leaves and root used in folk medicine for skin complaints, stings, wounds and colds",a:"Kuppameni, Kattu munja (കാട്ടു മുഞ്ഞ)"},
{n:"Krishna tulsi",m:"ചുവന്ന തുളസി",r:"Chuvanna thulasi",s:"Ocimum tenuiflorum",f:"Lamiaceae",c:"Medicinal",g:"leaf",
 b:"The purple-leaved form of holy basil, kept in a raised pot by the door.",
 d:"The dark, purple-stemmed form of holy basil, grown on a thulasithara platform in front of the house and watered every day. It is more pungent and peppery than the green Rama tulsi. The leaves go into cough remedies, herbal tea and temple offerings.",
 w:"House courtyards and temple grounds",t:"Flowers most of the year",u:"Cough remedy, tea, ritual",a:"Holy basil, Shyama tulsi"},
{n:"Moovila",m:"മൂവില",r:"Moovila",s:"Pseudarthria viscida",f:"Fabaceae",c:"Medicinal",g:"pinnate",
 b:"Three leaflets (moo-ila) and sticky pink flowers; a root of the Ayurvedic pharmacy.",
 d:"A sticky, hairy undershrub with leaves of three leaflets — the Malayalam name means ‘three leaves’. It bears small pink flowers in branched sprays and flat pods holding four to six seeds. The root is used in Kerala as salaparni, one of the herbs in the classical dashamoola group of ten roots.",
 w:"Peninsular India and Sri Lanka; open scrub and grassland",u:"Root used in Ayurveda for fever, cough, heart and digestive complaints",a:"Salaparni (Sanskrit)",e:"Vulnerable — as assessed by Kerala's State Medicinal Plants Board"},

/* ---------------- Spices ---------------- */
{n:"Malabar tamarind",m:"കുടംപുളി",r:"Kudampuli",s:"Garcinia cambogioides",f:"Clusiaceae",c:"Spices",g:"leaf",
 b:"The smoked black rind that makes Kerala fish curry taste like itself.",
 d:"A small evergreen tree with ribbed, pumpkin-shaped yellow fruit. The rind is dried and smoked until black and leathery, then added whole to fish curry. Listed here under the name used in the campus survey; the Kudampuli of Kerala kitchens is also widely labelled Garcinia gummi-gutta (formerly G. cambogia), and botanists do not all agree on where the line between these names falls.",
 w:"Western Ghats slopes and homesteads",t:"Harvest in the monsoon months",u:"Souring agent in fish curry; hydroxycitric acid extracted for supplements",a:"Chigiri, brindle berry"},
{n:"Cinnamon",m:"കറുവപ്പട്ട",r:"Karuvapatta",s:"Cinnamomum verum",f:"Lauraceae",c:"Spices",g:"leaf",
 b:"The spice is inner bark, peeled and rolled while wet.",
 d:"Trees are cut back hard so they throw up straight shoots, and the bark is stripped from those and rolled into quills. The new leaves flush bright red before turning glossy green, and have three strong veins from the base. The species is native to Sri Lanka.",
 w:"Midland homesteads and small plantations",t:"Bark harvested in the wet months",u:"Spice, bark oil, leaf oil"},
{n:"Makrut lime",m:"വലിയനാരകം",r:"Valiyanaregam",s:"Citrus hystrix",f:"Rutaceae",c:"Spices",g:"leaf",
 b:"Hourglass-shaped double leaves and a knobbly, bumpy little fruit.",
 d:"A thorny shrub or small tree whose leaves look like two leaves joined end to end, because the stalk is broad and leaf-like. The small green fruit has deeply wrinkled, bumpy skin. The fragrant leaves are a key ingredient of Thai and Southeast Asian curries.",
 w:"Native to tropical Southeast Asia; homestead gardens",t:"Fruits through much of the year",u:"Leaves and rind in cooking; juice as a cleanser for clothes and hair",e:"Introduced from Southeast Asia",a:"Thai lime"},

/* ---------------- Ornamental ---------------- */
{n:"Copperleaf",r:"Copper plant",s:"Acalypha wilkesiana",f:"Euphorbiaceae",c:"Ornamental",g:"broad",
 b:"Mottled copper, red and green leaves that look good all year.",
 d:"An evergreen shrub up to 3 metres grown for its large, broad leaves splashed in copper, red, pink and green. Male flowers hang in long catkin-like spikes; female flowers are shorter and hidden among the leaves. It is a staple of tropical hedges and borders.",
 w:"Native to Vanuatu and the Pacific Islands; hedges and borders",u:"Ornamental hedge; leaf extracts used in traditional medicine for skin fungus",e:"Introduced from the Pacific Islands",a:"Jacob's coat, fire dragon"}
];

/* catalogue order: by group, then alphabetical */
(function () {
  const order = ["Trees", "Fruit", "Medicinal", "Flowering", "Palms", "Spices", "Ornamental"];
  FLORA.sort((a, b) => order.indexOf(a.c) - order.indexOf(b.c) || a.n.localeCompare(b.n));
})();

/* Nakshatra trees (janma nakshatra vriksham): the tree traditionally
   linked to each of the 27 birth stars of the Malayalam calendar.
   Scientific name -> [star number, star, star in Malayalam] */
const STAR_TREES = {
  "Strychnos nux-vomica": [1, "Ashwathi", "അശ്വതി"],
  "Phyllanthus emblica": [2, "Bharani", "ഭരണി"],
  "Ficus racemosa": [3, "Karthika", "കാർത്തിക"],
  "Syzygium cumini": [4, "Rohini", "രോഹിണി"],
  "Senegalia catechu": [5, "Makayiram", "മകയിരം"],
  "Butea monosperma": [11, "Pooram", "പൂരം"],
  "Spondias pinnata": [13, "Atham", "അത്തം"],
  "Aegle marmelos": [14, "Chithira", "ചിത്തിര"],
  "Terminalia arjuna": [15, "Chothi", "ചോതി"],
  "Mimusops elengi": [17, "Anizham", "അനിഴം"],
  "Aporosa cardiosperma": [18, "Thrikketta", "തൃക്കേട്ട"],
  "Vateria indica": [19, "Moolam", "മൂലം"],
  "Artocarpus heterophyllus": [21, "Uthradam", "ഉത്രാടം"],
  "Mitragyna parvifolia": [24, "Chathayam", "ചതയം"],
  "Tectona grandis": [25, "Pooruruttathi", "പൂരുരുട്ടാതി"],
  "Mangifera indica": [26, "Uthrattathi", "ഉത്രട്ടാതി"],
  "Madhuca longifolia var. latifolia": [27, "Revathi", "രേവതി"]
};
FLORA.forEach(r => {
  const s = STAR_TREES[r.s];
  if (s) { r.nkn = s[0]; r.nk = s[1]; r.nkm = s[2]; }
});

const BUTTERFLIES = [
{"n":"Plain tiger","s":"Danaus chrysippus","f":"Nymphalidae","c":"Milkweed","g":"fly2","b":"Orange with black-tipped forewings; the most-copied butterfly in India.","d":"Common in open, dry, disturbed ground. Its toxicity has produced a well-studied mimicry complex — the female danaid eggfly is a close copy of it.","w":"Open scrub, waste ground, coastal dunes","t":"Year round","u":"Larval host: Calotropis and other milkweeds"},
{"n":"Common tiger","s":"Danaus genutia","f":"Nymphalidae","c":"Milkweed","g":"fly2","b":"A larger, bolder tiger with black veins traced sharply across orange wings.","d":"Easily mistaken for the plain tiger but larger, with black veins standing out boldly against the orange ground colour and a wide black hindwing margin dotted with white spots. One of several tiger-pattern milkweed butterflies flying together in the Ghats, and just as distasteful to birds thanks to its toxic host plants.","w":"Gardens, forest edges and scrub, from the coast to over 2,000 m","t":"Year round, with migratory movements around the monsoon","u":"Larval host: Cryptolepis, Tylophora and other milkweeds"},
{"n":"Common crow","s":"Euploea core","f":"Nymphalidae","c":"Milkweed","g":"fly2","b":"The unhurried brown-black butterfly of every garden.","d":"Glossy brown-black with a rim of white spots, flapping and gliding in a way that makes it easy to follow. Toxic from its milkweed diet, and the model for several harmless mimics.","w":"Gardens, plantations, scrub, forest","t":"Year round","u":"Larval host: figs, oleander, milkweeds"},
{"n":"Blue tiger","s":"Tirumala limniace","f":"Nymphalidae","c":"Milkweed","g":"fly2","b":"Migrates across the Ghats in thousands, twice a year.","d":"Pale blue streaks on black-brown wings and a slow sailing flight. Large mixed migrations of blue tigers, dark blue tigers and double-branded crows cross Kerala before and after the monsoon, sometimes roosting in dense clusters.","w":"Everywhere from gardens to forest, 0 to 2,000 m","t":"Migration peaks around April and October","u":"Larval host: Tylophora and other milkweeds"},
{"n":"Commander","s":"Moduza procris","f":"Nymphalidae","c":"Nymphs","g":"fly1","b":"A fast, sharp-flying forest butterfly banded in cream across rich brown-orange wings.","d":"Named for its brisk, purposeful flight and habit of returning to the same sunlit perch on a leaf tip. A broad cream-white band crosses both wings on a warm orange-brown ground, with a paler, more intricately patterned underside. Males often gather at damp patches on forest paths and stream banks to drink minerals.","w":"Forest edges, shaded paths and stream banks","t":"Year round, more often seen after rain","u":"Larval host: Wendlandia, Ixora and other Rubiaceae"}
];


